Enchancement/semantic matching
dodona-edu/dolos pull request #726
Opened 2022-04-12 20:04 UTC by AurisAudentis

2022-06-02 13:32 UTC, rien requested changes
Unfortunately, loading the page is now very slow and is being unresponsive in the process. While this is a good addition to Dolos itself, I don't think it is worth giving up the responsiveness.

Do you think it would be possible, to make this optional or calculate this in the background? If not, I think we should try speeding this up as much as possible, or reconsider moving this calculation to the CLI.

The compare view seems to be broken in some cases (no highlighted parts, and the code blocks are shown fully instead of in a scroll block).

2022-06-02 13:32 UTC, rien commented on web/src/components/CompareSide.vue
> +  <div style="height: 100%">
Can this be moved to the `<style>` block in this component?

2022-06-02 13:32 UTC, rien commented on web/src/components/FragmentList.vue
> +      // this.dataTableSelection = [this.fragmentsWithId[newVal]];
This function doesn't seem to do anything anymore, should it be removed?

2022-06-03 12:05 UTC, AurisAudentis commented on lib/src/lib/analyze/index.ts
> +  //private readonly index: Map<Hash, Array<Occurrence>> = new Map();
Yes, using this setup with local variables was necessary to enable the instance of this class to be re-used in SemanticAnalyzer to annotate the AST's as required for the algorithm.

2022-06-03 13:35 UTC, AurisAudentis commented on lib/src/lib/analyze/SemanticAnalyzer.ts
> +export class SemanticAnalyzer {
This analysis code is not specific to the browser (it is not responsible directly for visualisation) or to the CLI code (running the analysis). It is display-independent algorithmic code, which I felt fits better in the platform-independent 'lib'.

I still remain convinced the 'lib' package is the appropriate place to store this, especially considering the step of moving the execution of the algorithm to the CLI at analysation time. Do you feel it should be moved?

2022-06-20 09:37 UTC, rien requested changes
- There are some `yarn.lock` files and `package-lock.json` files added that should be removed
- It seems you changed the files in the `web/public/data` with python files analyzed with the language parser? Is there a specific reason for this?

2022-06-20 09:37 UTC, rien commented on cli/src/cli/commands/run.ts
> +        "Using the semantic analysis augment in Dolos",
```suggestion
        "Enable a semantic analysis on the matched fragments",
```

2022-06-20 09:37 UTC, rien commented on cli/src/cli/commands/run.ts
> +        "Length of the smallest semantic match",
Is this the length in tokens?

2022-06-20 09:37 UTC, rien commented on lib/src/lib/analyze/SemanticAnalyzer.ts
> +  private async semanticAnalysisOneFile(
I think this is still something that can be changed?

2022-06-20 09:37 UTC, rien commented on lib/src/lib/analyze/index.ts
> +    tokenizedFiles.forEach(t => t.kgrams.splice(0, t.kgrams.length));
I think this doesn't do anything?

2022-06-20 09:37 UTC, rien commented on web/src/components/CompareSide.vue
> +import { NodeStats } from "@dodona/dolos-lib/dist/lib/analyze/SemanticAnalyzer";
```suggestion
import { NodeStats } from "@dodona/dolos-lib";
```
And `NodeStats` will probably need to be exported by the lib.

2022-06-20 11:57 UTC, rien approved these changes
:+1:

2022-06-20 15:11 UTC, merged