Implement new API stores & refactor App component
dodona-edu/dolos pull request #758
Opened 2022-06-21 09:12 UTC by maartenvn

This PR includes a new API system, implemented inside Pinia stores and a refactor of the App.vue component.

Remarks:
* As of right now the stores are defined and hydrated with data, but not yet used throughout the app.
* Because of the refactor of app.vue the anonymize button does no longer work. This will be fixed once the other components are using the Pinia stores.
  * *This isn't really an issue right now, as we are not yet merging with main, but something to keep in mind.*

Reference #746, #754

2022-06-21 14:10 UTC, rien requested changes
Looking good!

It seems like the PR #726 was merged in main after the `refactor` branch was split off. There were some changes added to the API there as well. Can you look to rebase or merge your PR's with main?

2022-06-21 14:45 UTC, maartenvn commented on web/src/App.vue
> +      await usePairStore().hydrate();
This is fixed in the next PR (#759) 😄

2022-06-21 14:46 UTC, maartenvn commented on web/src/api/stores/settings.store.ts
> +  // Is the names should be anonymized.
Will apply this in the next PR on this branch (this store has been renamed in #759)

2022-06-21 14:51 UTC, maartenvn commented on web/src/api/stores/settings.store.ts
> +  // Is the names should be anonymized.
Fixed in 92c79c22c96f33c891e23e09f6ab82e32105c669

2022-06-22 07:26 UTC, rien approved these changes

2022-06-22 07:40 UTC, merged