Improve UI
dodona-edu/dolos pull request #841
Opened 2022-08-10 14:14 UTC by maartenvn

# Improve UI of the application

## Overview
- [ ] Align text left, instead of centering
- [ ] Similarity histogram: origin (0, 0) should be bottom left instead of top left

## File pairs
- [ ] Similarity: show as percentage instead of fractional number. For example, with progress indicators:
![image](https://user-images.githubusercontent.com/3226995/183917549-aa0f9310-d4c8-402a-87db-84a19d830e39.png)
- [ ] Navigation with shortcuts: left/right arrow to go to previous/next page, up/down to select row, enter to go to compare view

## Similarity slider
- [ ] Changing the slider lets the user lose the original position, mark this position as a tick (if possible) on the slider and enable a reset.

## Cluster view
- [ ] Hide pagination of pairs table if less than 10 items.

## General
- [ ] Add back-buttons / breadcrumbs where possible
- [ ] Check the colors for consistency (there is a difference between d3's blue and vuetify's blue for example) and contrast (d3's orange is not enough contrast with the background).

2022-08-10 14:15 UTC, maartenvn commented
I am working on a new overview page:

![image](https://user-images.githubusercontent.com/6013068/183923947-40a212de-12d8-477c-9de0-674e8900495d.png)

There is still a lot of white space on the first card on the left. If anyone has some ideas to put additional information or something else let me know.

@rien @bmesuere

2022-08-12 07:47 UTC, maartenvn commented
A reset button was added to the cut-off slider to allow reset to the initial value:

![image](https://user-images.githubusercontent.com/6013068/184309030-d280a529-360e-46a5-ab91-94aa918d41a6.png)

2022-08-12 08:09 UTC, rien commented
- The symbols in the three middle cards (similarity-cutoff, highest similarity, clusters) could be confused with buttons. I would avoid putting it in a box with the primary color. Instead, you could set the icon as a gray "background" of the card?
- I think listing the labels itself (possibly with their color) in addition to the amount, would be useful.
- I would maybe invert the information rows: `404 files` instead of `Files: 404`.

2022-08-12 08:19 UTC, maartenvn commented
> * The symbols in the three middle cards (similarity-cutoff, highest similarity, clusters) could be confused with buttons. I would avoid putting it in a box with the primary color. Instead, you could set the icon as a gray "background" of the card?

![image](https://user-images.githubusercontent.com/6013068/184314220-4e9b3b0e-1314-442a-8f8c-8306cac5e533.png)

I changed the background color to a light blue. This should distinguish the card from a button.

2022-08-16 08:02 UTC, maartenvn commented
Improved UI for the selected cluster/node.

| Before | After |
| ------- | ------|
| ![image](https://user-images.githubusercontent.com/6013068/184828902-60c8632b-2726-4472-b230-a2644e7c3451.png) | ![image](https://user-images.githubusercontent.com/6013068/184828718-c3174e05-402f-4802-9d57-aaef533abb36.png) |

2022-08-16 08:35 UTC, maartenvn commented
![image](https://user-images.githubusercontent.com/6013068/184835564-cbfda965-99db-4b0f-8511-e50042511d6c.png)

Labels are now visible on the overview page.

2022-08-16 08:53 UTC, rien commented
These improvements are looking good :+1: 

##### Cluster
- If data is unavailable, I would omit the information. But there should be a nudge telling the user how they can add time-information next time. Maybe a timeline on the homepage that is disabled?
- Instead of "Author", I think using "Submission" is better, since it works for file names as well as student names.
- In addition, I don't know if we should show "Author:", "Label:", "Hand-in date:", I think the symbol is clear, and we could add a tooltip instead.
- I would use the colored circle again for the label, this will improve the recall.
- For "Selected cluster", I would invert the information:
  - **3** submissions in this cluster.
  - **100%** average similarity
 - If hand-in date is available, highlighting the first submitter in some way would be useful 

##### Overview
- I think it would look better to start the programming language with a capital letter.
- The label count can be useful as well "5 labels in this dataset"

2022-08-16 12:37 UTC, maartenvn commented
@rien This can be reviewed 🙂

2022-08-18 14:08 UTC, rien requested changes
The comparison page seems to be broken: the page does not load and the console spews out the error `r` is undefined.

There does also seem something weird happening on the cluster page: not all pairs are shown in the pairs table: a cluster with 7 submissions, only shows 6 pairs, bot there should be more.

2022-08-18 14:08 UTC, rien commented on web/src/d3-tools/GraphElementList.vue
> +        <th>File</th>
```suggestion
        <th>Submission</th>
```

2022-08-18 14:08 UTC, rien commented on web/src/d3-tools/GraphElementListCard.vue
> +    <v-card-title> Files in this cluster </v-card-title>
```suggestion
    <v-card-title>Submissions in this cluster </v-card-title>

```

2022-08-18 14:08 UTC, rien commented on web/src/views/Overview.vue
> +                The highest similarity we've found between two files is {{ (highestSimilarity * 100).toFixed(0) }}%
```suggestion
                The highest similarity we've found between two submissions is {{ (highestSimilarity * 100).toFixed(0) }}%
```

2022-08-18 14:08 UTC, rien commented on web/src/views/Overview.vue
> +                Files are grouped into clusters based on their similarity.
```suggestion
                Submissions are grouped into clusters based on their similarity.
```

2022-08-18 14:08 UTC, rien commented on web/src/views/Overview.vue
> +                If a file pair has a similarity above the threshold, they will belong to the same cluster.
```suggestion
                If a submission pair has a similarity above the threshold, they will belong to the same cluster.
```

2022-08-18 14:08 UTC, rien commented on web/src/views/Overview.vue
> +            <div class="stat-card-subtitle text--secondary">Largest cluster: {{ largestCluster }} files</div>
```suggestion
            <div class="stat-card-subtitle text--secondary">Largest cluster: {{ largestCluster }} submissions</div>
```

2022-08-22 07:25 UTC, maartenvn commented on web/src/components/pair/SimilarityDisplay.vue
> +const color = computed(() => {
This is done in a later PR on a different branch

2022-08-22 07:26 UTC, maartenvn commented on web/src/d3-tools/GraphElementList.vue
> +  return DateTime.fromJSDate(time).toFormat("dd/MM hh:mm");
These time displays are extracted in a seperate component in an upcoming PR and in order to prevent merge conflicts I will change this later on.

2022-08-22 08:12 UTC, rien approved these changes

2022-08-22 10:51 UTC, merged